input/badfunc02.c:5:6:Error: name 'foo' already defined in this scope
